# Generated by Django 5.1.7 on 2025-04-03 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='uid',
        ),
    ]
