# Generated by Django 5.1.7 on 2025-04-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_userprofile_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('travel_agent', 'Travel Agent'), ('user', 'User')], default='User', max_length=20),
        ),
    ]
