# Generated by Django 5.1.7 on 2025-04-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Date',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
