# Generated by Django 5.1.7 on 2025-04-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('flight', 'Flight'), ('package', 'Package'), ('hotel', 'Hotel')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
