# Generated by Django 5.1.7 on 2025-04-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_booking_category_hotel_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='package',
            name='flights',
        ),
        migrations.RemoveField(
            model_name='package',
            name='hotels',
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_destinations', to='auth_app.destination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_sources', to='auth_app.destination'),
        ),
    ]
