# Generated by Django 5.1.7 on 2025-04-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_remove_package_available_seats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_connections', to='auth_app.destination')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_connections', to='auth_app.destination')),
            ],
        ),
    ]
