# Generated by Django 5.1.7 on 2025-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_destinationconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
