# Generated by Django 5.1.7 on 2025-04-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_remove_review_destination_review_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
