# Generated by Django 5.1.7 on 2025-04-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0010_flight_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='flight_icon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
