# Generated by Django 5.1.7 on 2025-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_flight_flight_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
