# Generated by Django 5.1.7 on 2025-04-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_hotel_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
