# Generated by Django 5.1.7 on 2025-04-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_package_price_alter_hotel_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
