# Generated by Django 5.1.7 on 2025-04-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_package_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
