# Generated by Django 5.1.7 on 2025-04-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0017_alter_package_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
