# Generated by Django 5.1.7 on 2025-04-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0018_alter_package_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='bookings', to='auth_app.flight'),
        ),
        migrations.AddField(
            model_name='booking',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='hotel_bookings', to='auth_app.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='package_bookings', to='auth_app.package'),
        ),
    ]
