# Generated by Django 5.1.7 on 2025-04-06 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_booking_flights_booking_hotels_booking_packages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flights',
            new_name='flight',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotels',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='packages',
        ),
        migrations.AddField(
            model_name='booking',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotel_bookings', to='auth_app.hotel'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_bookings', to='auth_app.package'),
        ),
    ]
