# Generated by Django 5.1.7 on 2025-04-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_rename_flights_booking_flight_remove_booking_hotels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flight',
            new_name='flights',
        ),
    ]
