# Generated by Django 5.1.7 on 2025-04-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_rename_flight_booking_flights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='hotel',
            new_name='hotels',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='package',
            new_name='packages',
        ),
    ]
