# Generated by Django 5.1.7 on 2025-04-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0022_rename_hotel_booking_hotels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='flights',
            field=models.ManyToManyField(blank=True, related_name='package_flights', to='auth_app.flight'),
        ),
        migrations.AddField(
            model_name='package',
            name='hotels',
            field=models.ManyToManyField(blank=True, related_name='package_hotels', to='auth_app.hotel'),
        ),
    ]
